name: Vercel Tailwind Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Ensure Tailwind & PostCSS
        run: |
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss init -p

      - name: Commit any missing files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tailwind.config.js postcss.config.js package.json package-lock.json
          git commit -m "Auto: ensure TailwindCSS & PostCSS installed" || echo "No changes to commit"
          git push origin main

      - name: Build project
        run: |
          npm run build
